services:
  gateway:
    build: ./API_Gateway_Microservice
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - flight
      - booking
      - payment
    networks:
      - app-network

  auth:
    build: ./Registeration-Login_Microservice
    ports:
      - "5000:5000"
    networks:
      - app-network

  flight:
    build: ./Flight_Microservice
    ports:
      - "5001:5001"
    networks:
      - app-network

  booking:
    build: ./Booking_Microservice
    ports:
      - "5002:5002"
    networks:
      - app-network

  payment:
    build: ./Payment_Microservice
    ports:
      - "5003:5003"
    networks:
      - app-network

networks:
  app-network: