upstream backend {
    server <EC2-2-PUBLIC-IP>:4000;
    server <EC2-3-PUBLIC-IP>:4000;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}