upstream auth_service {
    server auth1:5000;
    server auth2:5000;
}

upstream flight_service {
    server flight1:5001;
    server flight2:5001;
}

upstream booking_service {
    server booking1:5002;
    server booking2:5002;
}

upstream payment_service {
    server payment1:5003;
    server payment2:5003;
}

server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth_service;
    }

    location /flight/ {
        proxy_pass http://flight_service;
    }

    location /booking/ {
        proxy_pass http://booking_service;
    }

    location /payment/ {
        proxy_pass http://payment_service;
    }
}