upstream backend {
    server 32.199.176.88:4000;
    server 13.218.240.179:4000;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}